# Generated by Django 6.1 on 2026-09-16 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_05_clients_projects', '0002_changerequest_clientcommercialreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('task_submission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(db_column='submitted_by_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(db_column='task_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='module_05_clients_projects.task')),
            ],
            options={
                'db_table': 'ext_task_submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
