# Generated by Django 6.1 on 2026-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_05_clients_projects', '0003_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignee',
            name='review_status',
            field=models.CharField(choices=[('NONE', 'None'), ('IN_REVIEW', 'In Review'), ('NEEDS_FIXES', 'Needs Fixes')], default='NONE', max_length=20),
        ),
    ]
