# Generated by Django 6.1 on 2026-09-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('access_level_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_code', models.CharField(max_length=50, unique=True)),
                ('access_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'access_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfidentialityLevel',
            fields=[
                ('confidentiality_level_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level_code', models.CharField(max_length=50, unique=True)),
                ('level_name', models.CharField(max_length=100, unique=True)),
                ('security_rank', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'confidentiality_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_code', models.CharField(max_length=100, unique=True)),
                ('document_title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_version_number', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('is_confidential', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('document_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentPerson',
            fields=[
                ('document_person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=50, unique=True)),
                ('type_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('document_version_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=150, null=True)),
                ('storage_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_reference', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_algorithm', models.CharField(blank=True, max_length=50, null=True)),
                ('checksum_value', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_current', models.BooleanField()),
            ],
            options={
                'db_table': 'document_version',
                'managed': False,
            },
        ),
    ]
