# Generated by Django 6.1 on 2026-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_06_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDocumentGeneration',
            fields=[
                ('ai_document_generation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generation_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('generation_model', models.CharField(blank=True, max_length=150, null=True)),
                ('prompt_text', models.TextField(blank=True, null=True)),
                ('generation_status', models.CharField(max_length=30)),
                ('requested_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_document_generation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessRule',
            fields=[
                ('document_access_rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_access_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('document_approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(default=1)),
                ('approval_status', models.CharField(default='PENDING', max_length=30)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_approval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentProject',
            fields=[
                ('document_project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentRetention',
            fields=[
                ('document_retention_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('retention_start_date', models.DateField()),
                ('retention_period_days', models.IntegerField(blank=True, null=True)),
                ('retention_end_date', models.DateField(blank=True, null=True)),
                ('disposition_action', models.CharField(default='REVIEW', max_length=50)),
                ('legal_hold', models.BooleanField(default=False)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_retention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('document_template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_content', models.TextField(blank=True, null=True)),
                ('template_format', models.CharField(max_length=30)),
                ('version_number', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_template',
                'managed': False,
            },
        ),
    ]
