# Generated by Django 6.1 on 2026-09-17 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_06_documents', '0002_aidocumentgeneration_documentaccessrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClientApproval',
            fields=[
                ('document_client_approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(db_column='approved_by_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_approval', to='module_06_documents.document')),
            ],
            options={
                'db_table': 'ext_document_client_approval',
            },
        ),
    ]
