# Generated by Django 6.1 on 2026-09-05 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_03_training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('intern_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intern_code', models.CharField(max_length=50, unique=True)),
                ('internship_start_date', models.DateField()),
                ('internship_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('conversion_status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'intern',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipRecommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recommendation_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_by', models.ForeignKey(db_column='recommended_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_recommendations_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_recommendations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(db_column='student_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='internship_recommendation', to='module_03_training.student')),
            ],
            options={
                'db_table': 'ext_internship_recommendation',
            },
        ),
    ]
