# Generated by Django 6.1 on 2026-09-07 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_04_interns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternReportingManagerHistory',
            fields=[
                ('intern_manager_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'intern_reporting_manager_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternWorklog',
            fields=[
                ('worklog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('login_time', models.CharField(blank=True, max_length=20, null=True)),
                ('logout_time', models.CharField(blank=True, max_length=20, null=True)),
                ('entries', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(db_column='intern_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='module_04_interns.intern')),
                ('reported_to_user', models.ForeignKey(blank=True, db_column='reported_to_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ext_intern_worklog',
                'unique_together': {('intern', 'work_date')},
            },
        ),
    ]
