# Generated by Django 6.1 on 2026-09-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_04_interns', '0002_internreportingmanagerhistory_internworklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternWorklog',
        ),
    ]
