# Generated by Django 6.1 on 2026-09-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_04_interns', '0003_delete_internworklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternAttendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'intern_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipProject',
            fields=[
                ('internship_project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'internship_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternTask',
            fields=[
                ('intern_task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'intern_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternTaskSubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_note', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern_task', models.OneToOneField(db_column='intern_task_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='submission_detail', to='module_04_interns.interntask')),
            ],
            options={
                'db_table': 'ext_intern_task_submission_detail',
            },
        ),
    ]
