# Generated by Django 6.1 on 2026-09-07 08:26

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_04_interns', '0004_internattendance_internshipproject_interntask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternTestingReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_text', models.TextField()),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment')),
                ('status', models.CharField(choices=[('NEEDS_FIXES', 'Needs Fixes'), ('APPROVED', 'Approved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('intern_task', models.ForeignKey(db_column='intern_task_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='testing_reports', to='module_04_interns.interntask')),
            ],
            options={
                'db_table': 'ext_intern_testing_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
