# Generated by Django 6.1 on 2026-09-12 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_04_interns', '0005_interntestingreport'),
        ('module_05_clients_projects', '0002_changerequest_clientcommercialreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternPerformance',
            fields=[
                ('performance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teamwork_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('problem_solving_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('improvement_areas', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'intern_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipCompletion',
            fields=[
                ('completion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=50)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internship_completion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipExtension',
            fields=[
                ('extension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('extension_reason', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internship_extension',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='interntestingreport',
            name='project_task',
            field=models.ForeignKey(blank=True, db_column='project_task_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testing_reports', to='module_05_clients_projects.projecttask'),
        ),
        migrations.AlterField(
            model_name='interntestingreport',
            name='intern_task',
            field=models.ForeignKey(blank=True, db_column='intern_task_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testing_reports', to='module_04_interns.interntask'),
        ),
        migrations.AddConstraint(
            model_name='interntestingreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('intern_task__isnull', False), ('project_task__isnull', True)), models.Q(('intern_task__isnull', True), ('project_task__isnull', False)), _connector='OR'), name='testing_report_exactly_one_task_type'),
        ),
    ]
