# Generated by Django 6.1 on 2026-09-16 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_04_interns', '0006_internperformance_internshipcompletion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interntestingreport',
            name='resolution_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='interntestingreport',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interntestingreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interntestingreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_column='resolved_by_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
    ]
