# Generated by Django 6.1 on 2026-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiEmail',
            fields=[
                ('ai_email_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ai_query_id', models.BigIntegerField(blank=True, null=True)),
                ('recipient_email', models.CharField(max_length=255)),
                ('cc_emails', models.TextField(blank=True, null=True)),
                ('bcc_emails', models.TextField(blank=True, null=True)),
                ('subject', models.TextField()),
                ('generated_body', models.TextField()),
                ('generation_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('generation_model', models.CharField(blank=True, max_length=150, null=True)),
                ('generation_status', models.CharField(default='DRAFT', max_length=30)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailApproval',
            fields=[
                ('email_approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approval_level', models.IntegerField(default=1)),
                ('approval_status', models.CharField(default='PENDING', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_approval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('email_batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_emails', models.IntegerField(default=0)),
                ('successful_emails', models.IntegerField(default=0)),
                ('failed_emails', models.IntegerField(default=0)),
                ('status', models.CharField(default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('email_delivery_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_provider', models.CharField(blank=True, max_length=150, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(default='QUEUED', max_length=30)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('email_template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=100, unique=True)),
                ('template_name', models.CharField(max_length=200)),
                ('subject_template', models.TextField()),
                ('body_template', models.TextField()),
                ('template_format', models.CharField(default='HTML', max_length=30)),
                ('version_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('email_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_type_code', models.CharField(max_length=50, unique=True)),
                ('email_type_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_type',
                'managed': False,
            },
        ),
    ]
