# Generated by Django 6.1 on 2026-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentLead',
            fields=[
                ('department_lead_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department_lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('designation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('designation_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_number', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'designation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesignationDepartmentMap',
            fields=[
                ('map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'designation_department_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('attendance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(max_length=50)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeBranchHistory',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_branch_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('exit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exit_date', models.DateField()),
                ('exit_type', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('exit_interview_completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_exit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('approved_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_leave',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('leave_balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('leave_year', models.IntegerField()),
                ('allocated_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('remaining_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_leave_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePayrollReference',
            fields=[
                ('payroll_reference_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payroll_provider', models.CharField(max_length=100)),
                ('external_employee_id', models.CharField(max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_payroll_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePromotion',
            fields=[
                ('promotion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorklog',
            fields=[
                ('worklog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('login_time', models.CharField(blank=True, max_length=20, null=True)),
                ('logout_time', models.CharField(blank=True, max_length=20, null=True)),
                ('entries', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_worklog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('employment_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employment_type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employment_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternOnboarding',
            fields=[
                ('onboarding_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intern_id', models.BigIntegerField(unique=True)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documents_shared', models.BooleanField(default=False)),
                ('signed_documents_received', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('designation_stipend_assigned', models.BooleanField(default=False)),
                ('offer_letter_acknowledged', models.BooleanField(default=False)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('welcome_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('login_credentials_provided', models.BooleanField(default=False)),
                ('onboarded_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intern_onboarding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('leave_type_code', models.CharField(max_length=30)),
                ('leave_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDepartmentHistory',
            fields=[
                ('department_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_department_history',
                'managed': False,
            },
        ),
    ]
