# Generated by Django 6.1 on 2026-09-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('access_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('resource_type', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_status', models.CharField(default='SUCCESS', max_length=20)),
                ('session_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_reference', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'access_log',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('system_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('event_source', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_status', models.CharField(default='SUCCESS', max_length=20)),
                ('event_message', models.TextField(blank=True, null=True)),
                ('event_payload', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_event',
                'ordering': ['-occurred_at'],
                'managed': False,
            },
        ),
    ]
