from django.urls import path

from .views import (
    AttendanceCheckInView,
    AttendanceCheckOutView,
    AttendanceTodayView,
    BranchListView,
    DepartmentDetailView,
    DepartmentListView,
    DesignationDetailView,
    DesignationListView,
    EmployeeAvatarUploadView,
    EmployeeDetailView,
    EmployeeListCreateView,
    EmploymentTypeListView,
    LeaveRequestApproveView,
    LeaveRequestListCreateView,
    LeaveRequestRejectView,
    LeaveSummaryView,
    LeaveTypeListView,
    MyAttendanceView,
    MyLeaveView,
    InternOnboardingUpdateView,
    MyWorklogView,
    OnboardingInternsView,
    TeamWorklogsView,
    WorklogsOrgView,
)

urlpatterns = [
    path("employees/", EmployeeListCreateView.as_view(), name="employee-list-create"),
    path("employees/<int:pk>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("employees/<int:pk>/avatar/", EmployeeAvatarUploadView.as_view(), name="employee-avatar-upload"),
    path("branches/", BranchListView.as_view(), name="branch-list"),
    path("departments/", DepartmentListView.as_view(), name="department-list"),
    path("departments/<int:pk>/", DepartmentDetailView.as_view(), name="department-detail"),
    path("designations/", DesignationListView.as_view(), name="designation-list"),
    path("designations/<int:pk>/", DesignationDetailView.as_view(), name="designation-detail"),
    path("employment-types/", EmploymentTypeListView.as_view(), name="employment-type-list"),
    path("attendance/today/", AttendanceTodayView.as_view(), name="attendance-today"),
    path("attendance/check-in/", AttendanceCheckInView.as_view(), name="attendance-check-in"),
    path("attendance/check-out/", AttendanceCheckOutView.as_view(), name="attendance-check-out"),
    path("attendance/me/", MyAttendanceView.as_view(), name="attendance-me"),
    path("leave/types/", LeaveTypeListView.as_view(), name="leave-type-list"),
    path("leave/summary/", LeaveSummaryView.as_view(), name="leave-summary"),
    path("leave/requests/", LeaveRequestListCreateView.as_view(), name="leave-request-list-create"),
    path("leave/requests/<int:pk>/approve/", LeaveRequestApproveView.as_view(), name="leave-request-approve"),
    path("leave/requests/<int:pk>/reject/", LeaveRequestRejectView.as_view(), name="leave-request-reject"),
    path("leave/me/", MyLeaveView.as_view(), name="leave-me"),
    path("worklogs/", WorklogsOrgView.as_view(), name="worklog-org"),
    path("worklogs/me/", MyWorklogView.as_view(), name="worklog-me"),
    path("worklogs/team/", TeamWorklogsView.as_view(), name="worklog-team"),
    path("onboarding/interns/", OnboardingInternsView.as_view(), name="onboarding-interns-list"),
    path("onboarding/interns/<int:intern_id>/", InternOnboardingUpdateView.as_view(), name="onboarding-intern-update"),
]
