# Generated by Django 6.1 on 2026-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('personal_email', models.CharField(blank=True, max_length=255, null=True)),
                ('education_summary', models.CharField(blank=True, max_length=300, null=True)),
                ('source', models.CharField(default='other', max_length=20)),
                ('status', models.CharField(default='new', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeeInstallment',
            fields=[
                ('student_fee_installment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_fee_installment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('student_fee_payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('plan_type', models.CharField(default='full', max_length=10)),
                ('installment_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_fee_payment',
                'managed': False,
            },
        ),
    ]
