# Generated by Django 6.1 on 2026-09-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0001_initial'),
        ('module_03_training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('recording_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(help_text='Google Drive / YouTube (unlisted) / Zoom / Teams recording link', max_length=1000)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='module_03_training.batch')),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings_shared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ext_class_recording',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceNotification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='absence_notifications', to='module_03_training.enrollment')),
            ],
            options={
                'db_table': 'ext_absence_notification',
                'unique_together': {('enrollment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RecordingView',
            fields=[
                ('view_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(db_column='enrollment_id', on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to='module_03_training.enrollment')),
                ('recording', models.ForeignKey(db_column='recording_id', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='local_extensions.classrecording')),
            ],
            options={
                'db_table': 'ext_recording_view',
                'unique_together': {('recording', 'enrollment')},
            },
        ),
    ]
