# Generated by Django 6.1 on 2026-09-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0002_classrecording_absencenotification_recordingview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid_till_date', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(db_column='enquiry_id', on_delete=django.db.models.deletion.CASCADE, to='local_extensions.enquiry')),
                ('installment', models.ForeignKey(db_column='installment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_extensions.studentfeeinstallment')),
            ],
            options={
                'db_table': 'ext_invoice',
                'ordering': ['-generated_at'],
            },
        ),
    ]
