# Generated by Django 6.1 on 2026-09-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0003_invoice'),
        ('module_03_training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLog',
            fields=[
                ('topic_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='topic_logs', to='module_03_training.batch')),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ext_topic_log',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
