# Generated by Django 6.1 on 2026-09-04 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0004_topiclog'),
        ('module_03_training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('student_task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_code', models.CharField(max_length=255)),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rows_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='module_03_training.batch')),
                ('generated_by', models.ForeignKey(db_column='generated_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ext_generated_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
