# Generated by Django 6.1 on 2026-09-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='leave_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='leave_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
