# Generated by Django 6.1 on 2026-09-04 07:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0007_message_category_message_leave_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_note', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, help_text='One link per line — Drive, GitHub, etc.', null=True)),
                ('cc_email', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_task', models.OneToOneField(db_column='student_task_id', on_delete=django.db.models.deletion.CASCADE, related_name='submission_detail', to='local_extensions.studenttask')),
            ],
            options={
                'db_table': 'ext_task_submission_detail',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission_detail', models.ForeignKey(db_column='submission_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='local_extensions.tasksubmissiondetail')),
            ],
            options={
                'db_table': 'ext_submission_attachment',
            },
        ),
    ]
