# Generated by Django 6.1 on 2026-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0008_tasksubmissiondetail_submissionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmissiondetail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasksubmissiondetail',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
