# Generated by Django 6.1 on 2026-09-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0011_remove_notification_notif_type_and_more'),
        ('module_03_training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_assessment', models.OneToOneField(db_column='student_assessment_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='interview_detail', to='module_03_training.studentassessment')),
            ],
            options={
                'db_table': 'ext_mock_interview_detail',
            },
        ),
    ]
