# Generated by Django 6.1 on 2026-09-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_extensions', '0012_mockinterviewdetail'),
        ('module_03_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='module_03_training.batch'),
        ),
    ]
